=== andrewrlee/vendor-specific-media-type-validation/src/main/resources/product-acme-v1-schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Product set",
    "type": "array",
    "items": {
        "title": "Product",
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "id": {
                "description": "The unique identifier for a product",
                "type": "number"
            },
            "name": {
                "type": "string"
            },
            "price": {
                "type": "number",
                "exclusiveMinimum": 0
            },
            "date_produced": {
                "type": "string",
              "format": "date-time"
            },
            "catalog_id": {
                "type": "string"
            },
            "tags": {
                "type": "array",
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "uniqueItems": true
            },
            "dimensions": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "length": {"type": "number"},
                    "width": {"type": "number"},
                    "height": {"type": "number"}
                },
                "required": ["length", "width", "height"]
            },
            "warehouseLocation": {
                "description": "Coordinates of the warehouse with the product",
                "$ref": "http://json-schema.org/geo"
            }
        },
        "required": ["id", "name", "price", "date_produced", "catalog_id"]
    }
}

=== andrewrlee/vendor-specific-media-type-validation/src/test/resources/requests/request-acme-product-v1.json
[
  {
    "id" : 1111,
    "name": "Hedge Cutters",
    "price": 12.23,
    "date_produced" : "2015-09-28T10:40:00+02:00",
    "catalog_id" : "111",
    "tags" : ["garden"],
    "dimensions" : {
      "length": 1000,
      "width" :  12.21,
      "height": 122
    },
    "warehouseLocation" : {
      "latitude": 1.0,
      "longitude" : 2.0
    }
  }
]
